# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q77sIJ0EGHVxbKIKDk4Sb1C8fbq9hx2c
"""

!pip install gtts

from gtts import gTTS
import os
text="Assalomu alaykum hurmatli talabalar"
language="tr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_tr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="tr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_tr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="ru"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ru.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="en"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_en.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="ar"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ar.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="fr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_fr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="zh"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_zh.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="zh-TW"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_zh-TW.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="de"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_de.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="es"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_es.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="ja"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ja.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="ko"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ko.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzuraman. Biz hozir sun'iy intellekt darsidamiz."
language="it"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_it.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)